# This is a basic workflow to help you get started with Actions

name: CI/CD
on:
  schedules:
    - cron: "0 0 * * *"
      displayName: Daily midnight build
      branches:
        include:
        - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo "Everything is okay"

