# This is a basic workflow to help you get started with Actions

name: CI/CD
on:
  push:
    branches: [ master ]
  pull_request_review_comment:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5,17 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo "Everything is okay"

